name: Build
on: [push, repository_dispatch]
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: '^1.17.1'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Fmt, Vet, Lint
      run: make linters

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: '^1.17.1'

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Test
      run: make test

  docs:
    name: Docs
    needs: [linting, test]
    if: endsWith(github.ref, '/master') == true
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      run: brew install pandoc

    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Docs
      run: make docs

    - name: Assume AWS Deploy Role
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID_TESTING }}:role/CI-ECS-Deploy
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy
      run: make deploy_docs
